parameters:
    ten24cmsgenericcmswebsitebundle.admin_menu_adaptor.class: Ten24\GenericCMS\WebsiteBundle\Helper\Menu\AdminMenuAdaptor
services:
    ten24genericcmswebsitebundle.admin_menu_adaptor:
        class: %ten24cmsgenericcmswebsitebundle.admin_menu_adaptor.class%
        arguments: ["@security.context"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
