imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Framework configuration
framework:
    esi:             ~
    fragments:       { path: /_fragment }
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1
        assets_base_url: %templating.assets_base_url%
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        %session_prefix%
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# This is all configured in parameters.yml for ULTIMATE portability!!!
assetic:
    debug: "%kernel.debug%"
    use_controller: %use_assetic_controller%
    filters:
        cssrewrite: ~
        sass: ~
        scss: ~
        uglifyjs2: ~
        uglifyjs: ~
        uglifycss: ~
        jpegoptim:
            bin: jpegoptim
            strip_all: true
            max: 85
            apply_to: "\.jpe?g$"
        optipng:
            bin: optipng
            apply_to: "\.png$"
            level: 3
        jpegtran:
            bin: jpegtran
            apply_to: "\.jpe?g$"
            optimisation: true
            progressive: true


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: "%database_server_version%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    port:       "%mailer_port%"
    spool:     { type: memory }